### ISSUE TITLE
Don't transliterate period

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/indic_transliteration#10]
When I transliterate period (`.`) from slp1 to itrans, I get `|`. There is no purpose to it.
I may be wrong.
Why I am concerned is that I get 01|0001 for 01.0001

`|` is not at all used in Devanagari / other transliterations also. Period is more native.

Wherever period is depicted as `|`, kindly keep it unchanged.

@vvasuki any idea ?

**Comment by vvasuki** [comment]
>‌ When I transliterate period (`.`) from slp1 to itrans, I get `|`... `|` is not at all used in Devanagari / other transliterations also. Period is more native.

This is actually expected behavior - The schemes (as implemented in sanscript) is defined so that daNDa of devanAgarI is represented by  `|` in ITRANS and `.` in SLP1. I've seen people use these characters for that purpose - it's possible that this is why they were chosen for this implementation. It's possible to define new variants, of course.

> Why I am concerned is that I get 01|0001 for 01.0001

Why don't you contribute a new option (see [here](https://github.com/sanskrit-coders/indic_transliteration/blob/a7a87efa808b51d55db3820d50fc215dcd99d2c9/indic_transliteration/sanscript.py#L351))  which is used at [this place](https://github.com/sanskrit-coders/indic_transliteration/blob/a7a87efa808b51d55db3820d50fc215dcd99d2c9/indic_transliteration/sanscript.py#L277) to revert regex patterns like `(\d+)[|।](\d+)`  to `\1.\2`in case the source scheme is wx or slp1 (along with a test)?

**Comment by drdhaval2785** [comment]
I changed my code to take care of this. Not a problem for me right now.
If there are more takers in future this library change may be taken up.
