### ISSUE TITLE
Add extended character support to more languages

### ISSUE THREAD

**Issue by karthikraman** [sanskrit-coders/indic_transliteration#5]
Particularly for South Indian languages with hrasva 'e', 'o' etc. Perhaps, we should have new "scripts" called XHK, XDEVANAGARI, XTAMIL etc.?

Or alternatively, HK can remain as HK and only XDEVANAGARI can be added to `sanscript.py` itself. TAMIL should be extended, in any case.

e.g. DEVANGARI: e & E can translate to 'ए', while in XDEVANAGARI, they will translate to 'ऎ' and 'ए' respectively... Request @vvasuki to review this idea.

**Comment by Shreeshrii** [comment]
In sanscript being used for sanskritdocuments.org, I have the following mapping for ITRANS vowels:

`   vowels: 'a A i I u U RRi RRI LLi LLI ^e e ai ^o o au'.split(' '), `

This uses ^e and ^o for hrsva e and o. 

This makes it easier to use same encoding scheme for all languages, though is NOT in sync with the current usage in South Indian languages, which uses e and o for hrsva and E and O for deergha.

**Comment by vvasuki** [comment]
Thanks @Shreeshrii  - that seems to be an elegant solution, which can be added to sanscript (<-- we will gratefully accept your modification if you're so inclined); while the extant south Indian convention is being adapted in https://github.com/sanskrit-coders/indic_transliteration/issues/4 . This way, devanAgarI, in its full extended form will be supported in both sanscript and xsanscript. @karthikraman अत्र तवाभिप्रायः?

**Comment by Shreeshrii** [comment]
Arun is going to merge the changes in sanscript.

https://github.com/sanskrit/sanscript.js/pull/7#issuecomment-325553413

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by karthikraman** [comment]
I think this is a great idea, and I'd integrate all of this into XDEVANAGARI, inside of `sanscript.py`. Then, `xsanscript.py` can go. I'll try to code that clean in a couple of days.

**Comment by vvasuki** [comment]
>‌I think this is a great idea, and I'd integrate all of this into XDEVANAGARI, inside of sanscript.py.

मया यदुक्तं तन्नावगतमिति भाति। XDEVANAGARI इति किमपि न भविष्यति। ऎ ए  ऒ ओ इत्यादिकं देवनागर्यक्षरमालायामिव भविष्यति। न तत्र प्रकारभेदः, एकैव देवनागरीमाला। अनुवादतन्त्र एव द्वैविध्यम् - ^e e ai ^o o इत्येके, e E ai o O इत्यपरे। एवम् अनुवादतन्त्रे द्वे - sanscript, sanskript-south।

**Comment by karthikraman** [comment]
Ah, I thought we were going to ignore e E o O scheme for ^e ^o. इदानीम् अवगतम्।

I would still argue for a regular devanagari (उभयोरपि अनुवादतन्त्रयोः), where e is "quashed" to E (hrasva to dirgha), since the letters like ऎ may be alien to most people, and is by definition not devanagari (is that a correct assumption?)

**Comment by vvasuki** [comment]
>  ऎ may be alien to most people, 
सत्यम्।

>‌ and is by definition not devanagari (is that a correct assumption?)

The assumption is partly incorrect. प्राचीनदेवनागर्यां नासीत्, आधुनिकदेवनागर्याम् विशिष्य दाक्षिणात्यशब्दलेखनार्थमेव निवेशितः। 

>‌ I would still argue for a regular devanagari (उभयोरपि अनुवादतन्त्रयोः)

एकैवास्त्विति मतिः। कुतः? येषाम् ऎ ऒ-आदीनाम् नास्ति परिचयः, ते तेषाम् न कुर्वन्तु नामोपयोगम्। यथाधुनिकदेवनागर्याम् अपि वर्तमानानाम् एतेषामक्षराणाम् अनुपयोक्तारो भवन्ति प्रायेण जनाः। अर्थात् - उपयोगे भेदो ऽस्तु, अक्षरमालायाम् न।

**Comment by shreevatsa** [comment]
IMO there are a lot of issues to be resolved / choices to be made (genuine design decisions) w.r.t. to transliteration between languages. I'm happy to see that the conversation is happening. (I think the comments on a Github issue may not be the best place to discuss… but whatever works.)

Here are some kinds of issues to discuss:

1. Language/script X has some sound/letter that is not present in Y. (E.g. Devanagari has dīrgha ṝ which some other script may not have, while Tamil script famously fails to distinguish between certain characters while having some distinctions that do not have a clear way of being expressed in Devanagari, Bengali does not distinguish between ba and va, etc.)

2. Language/script X has multiple ways of representing the same thing. (E.g. ITRANS may allow both `A` and `aa`, the khanda-ta situation in Bengali.)

3. Unicode lets you encode sequences of characters (like one vowel sign after another, or applying vowel signs to vowels, or even applying diacritics/combining characters from other scripts) -- what to do when they are encountered?

There are decisions to be made about all of these. To make them, one would first have to address more fundamental questions like:

1. What is the goal of transliteration here? Do we want it to be "conservative" (scream loudly when anything unexpected is seen, so that errors don't go undetected) or "liberal" (almost always do something reasonable, and thus possibly silently introduce errors)? 

2. Do we want our transliteration to be round-trippable? 

3. Purely library-usability features, like a feature / syntax to temporarily disable transliteration, etc. Many of these can (and probably should) be features of the frontend that the user interacts with, rather than baked into the library directly.

etc.

The answer(s) will depend on the goal(s); perhaps the library will need to have multiple modes to account for different users / use-cases.

We have enough half-baked or incompletely-thought-out transliteration libraries (I've written one or two myself); IMO the world doesn't need more of them. What we need is some principled and predictable behaviour, with awareness of the limitations -- the immediate task (IMO) is to clarify what the code should do, rather than write the code. 

That is why I was suggesting starting with tests, in the mailing list thread a while ago.

Here's an alternative proposal: 

-  look at the Unicode code charts for the relevant languages: http://www.unicode.org/charts/ Identify (document, discuss, decide) which subset of each script we'd like to cover, in which mode.
-  optionally, read through the Unicode descriptions for the Brahmic family of scripts. (First one is Chapter 12: http://www.unicode.org/versions/Unicode10.0.0/ch12.pdf, but IMO chapters 12 to 16 are all within scope: http://www.unicode.org/versions/Unicode10.0.0/ -- there's no fundamental reason the same library couldn't ultimately (in a later version) support Thai and Khmer too.)
- maybe even read the history/proposals for individual characters: e.g. a little bit about the short ऎ 
 in Devanagari is an additional proposal here: http://unicode.org/L2/L2009/09320-devshortvowels.pdf (I haven't found the original proposal)
- produce a "demo" so that people can see what the library does, and invite further feedback from experts

Of course it is possible to go arbitrarily deep and never get any work done (and I'm prone to that) :-) But IMO we should at least design the immediate library with some awareness of issues that are likely to arise later, and also (what I'm proposing) have at least documentation of the design decisions made, and keep discussion open (ongoing) so that more people can give their input even if they cannot read the code.

**Comment by shreevatsa** [comment]
1 Here are a couple of ways to look at transliteration:

Intensive definition: The scripts we're interested in all indicate a (more or less exact) correspondence from script to sound. X in Script 1 is a correct transliteration of Y in Script 2, if sound1(X) = sound2(Y).

This definition assumes that the input is "readable" (corresponds to a sound). It can provide some guidance for one way to resolve script-subsetting: if the target script contains multiple options, then it may be ok to map to anything that would be pronounced the same.

Intensive definition: There are certain correspondences between certain elements (some set of consonants, some set of vowels, some set of vowel signs) of a pair of scripts. The transliteration function should send each element from one script to the corresponding one in the other script.

This would include things like mapping the (unusual) Devanagari sequence अु to the corresponding Gujarati sequence કુ say.

2 The round-trip question: How will the transliteration library transliterate प्रउग into a Roman script, say, to avoid confusion with प्रौग?

Any sort of strategy may be ok, e.g. writing `pra-uga` (then the question may be whether प्र-उग gets transliterated to the same), or writing `pra{}uga` (a choice that I seem to have implemented in http://shreevatsa.appspot.com/sanskrit/transliterate.html at some point, though I have no memory of it), or throwing a warning, or deciding that it's an edge case and it's ok not to be round-trippable. But whatever is decided, IMO this decision should be documented as a design choice of the transliterator and be part of its description/testcases, and not an easter egg to be discovered by trying it out.

3 On the use-cases: note that the case of “I (the reader) just want to read this Bengali song in Devanagari script somehow, some sort of best effort is ok” is a different use case from “I want to present this Bengali song in Devanagari to readers, so that it is unambiguous and they read it exactly as a Bengali reader would”, even though both are transliterating between the same languages.

4 Another example: based on the use case, one may want to transliterate मंत्र as mantra (=मन्त्र) or as maṃtra. One may want to transliterate Hindi राम as rāma or as Rām. (If you disagree: that is good too, the choice is up to the implementor, but my point is that this disagreement is part of the design-choices of the library that must be documented.)

**Comment by karthikraman** [comment]
Many excellent points you make.

> On the use-cases: note that the case of “I (the reader) just want to read this Bengali song in Devanagari script somehow, some sort of best effort is ok” is a different use case from “I want to present this Bengali song in Devanagari to readers, so that it is unambiguous and they read it exactly as a Bengali reader would”, even though both are transliterating between the same languages.

This is somewhat what I'm trying to place as devangari (~best effort), and extended devangari (exact) - not sure.

Clearly, a one size fits all approach may not work --- so a transliterator tool must cater to (at least) the most popular use cases, having as many options as possible.

p.s. I've been using sanscript online at http://www.learnsanskrit.org/tools/sanscript and find it super useful as a pure devanagari translation tool.

**Comment by vvasuki** [comment]
नमामि @shreevatsa । यथोक्तं @karthikraman महाशयेन, बहून् उत्थापयसि चिन्त्यविषयान्। सङ्गृह्य खलु यदि DESIDERATA.md इति सञ्चिकां सृजेः, तन्नूनं स्यात्तराम् प्रयोजनाय। github-मध्य एवम् चर्चयेदमस्ति विशिष्टम् प्रयोजनम् - "चर्चाः कृतौ परिणमेयुस्तराम्, न खे लीयेरन् (ie ideas are grounded)"। 

उक्तविषयेषु - यथा @karthikraman-महाशयो ऽवदत् - ध्येयम् अस्य कोशस्यास्ति नैकस्यैव काङ्क्षितस्य पूरणम्। तेन ह्यत्र sanscript इत्येतद् विहाय तन्त्रांशान्तर-निवेषणम्। 

-------------

भद्र @karthikraman , "अनुवादतन्त्र एव द्वैविध्यम् - ^e e ai ^o o इत्येके, e E ai o O इत्यपरे। एवम् अनुवादतन्त्रे द्वे - sanscript, sanskript-south।" इति यदुक्तम्मया पुरा, तस्य पुनश्चिन्तनेनैवम् अभिप्रैमि  - "अनुवादतन्त्र एव द्वैविध्यम् - ^e e ai ^o o इत्येके, e E ai o O इत्यपरे। एवम् अनुवादतन्त्रे द्वे - hk, hk-south। द्वेऽपि भवितुमर्हतः sanscript-मध्ये।"

**Comment by shreevatsa** [comment]
Another thing I just remembered (that's why we should write things up!) that I had to implement -- apart from a script's consonants and vowels and vowel signs, which together form a reasonable basis for transliterating single (and typical) words, it seems reasonable that some more characters should "pass through" i.e. get transliterated to themselves: spaces in Latin script get transliterated into spaces in Devanagari, similarly with most punctuation (but danda…). But is there a limit? Should *all* unrecognized characters pass through untransliterated? E.g. if into a field that expects HK, someone types “squaw foxhunt”, should it get transliterated into “स्qउअw fओxहुन्त्”? Or should there be a warning/error shown? Or both? What is the list of all "allowed" characters that don't trigger such a warning? Does it include nonstandard punctuation like ‽ What about ZWNJ added in Devanagari to prevent a conjunct: how to transliterate it into some other script and back?

(Similarly: if someone uses a Devanagari avagraha in Kannada script, should we warn them? I think so — and especially if they use s instead of ऽ or ಽ respectively.

**Comment by vvasuki** [comment]
> Should all unrecognized characters pass through untransliterated? E.g. if into a field that expects HK, someone types “squaw foxhunt”, should it get transliterated into “स्qउअw fओxहुन्त्”? Or should there be a warning/error shown? Or both? What is the list of all "allowed" characters that don't trigger such a warning? Does it include nonstandard punctuation like ‽ 
> 
> (Similarly: if someone uses a Devanagari avagraha in Kannada script, should we warn them? I think so — and especially if they use s instead of ऽ or ಽ respectively.

I feel that the there are three distinct layers - script detection, transliteration, warning and the like. If we separate concerns in this manner, implementation and code sharing will be simpler..

> What about ZWNJ added in Devanagari to prevent a conjunct: how to transliterate it into some other script and back?

Good one to analyze at the transliteration level!

**Comment by shreevatsa** [comment]
Yes you're right about the distinct layers (user-facing versus the actual transliteration function, etc). Good point. But some of these decisions will need to get made anyway. E.g. the "transliterate" function could probably take only single words that are guaranteed to be valid, and it will be the caller's responsibility to ensure this and call as many times as necessary (splitting spaces and punctuation etc.)

**Comment by vvasuki** [comment]
@karthikraman Is there a reason why xdevanAgarI has roman digits? Unlike tamil-s who don't use their digits, kannaDa and devanAgarI users do. I think that the jyotiSha NAMES dict population might have required roman digits - but I removed that. Still, if we must, we should create new chimeric encodings like devanAarI_roman_digits to accommodate such cases (if they still exist)

**Comment by karthikraman** [comment]
Ah, it was a lazy fix -- to retain the behaviour that was initially there
-- not at all necessary. It can go.
